image: openjdk:11

before_script:
  # Enable the usage of sources over https
  - apt-get update -yqq
  - apt-get install apt-transport-https -yqq
  # Add keyserver for SBT
  - echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - mkdir -p /root/.gnupg
  - gpg --recv-keys --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --keyserver hkp://keyserver.ubuntu.com:80 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg
  # Install SBT
  - apt-get update -yqq
  - apt-get install sbt -yqq
  # Log the sbt version
  - sbt sbtVersion
  # Install make
  - apt-get install git make autoconf g++ flex bison build-essential -yqq
  # Install verilator (install a latest version)
  - git clone http://git.veripool.org/git/verilator
  - unsetenv VERILATOR_ROOT
  - unset VERILATOR_ROOT
  - cd verilator
  - git pull
  - git checkout v4.040
  - autoconf
  - ./configure
  - make -j$(nproc)
  - make install
  - cd .. && echo "Verilator installation DONE."

test:
  script:
    # Execute your project's tests
    - sbt clean test
